-- Migração segura para o projeto Supabase já existente.
-- Execute uma única vez no SQL Editor antes de disparar o workflow histórico.

ALTER TABLE public.execucoes
  ADD COLUMN IF NOT EXISTS voos_processados integer NOT NULL DEFAULT 0 CHECK (voos_processados >= 0),
  ADD COLUMN IF NOT EXISTS lotes_enviados integer NOT NULL DEFAULT 0 CHECK (lotes_enviados >= 0),
  ADD COLUMN IF NOT EXISTS erros integer NOT NULL DEFAULT 0 CHECK (erros >= 0);

CREATE TABLE IF NOT EXISTS public.historico_vra (
  id bigint generated by default as identity primary key,
  ano_mes text NOT NULL CHECK (ano_mes ~ '^\\d{4}-\\d{2}$'),
  icao_empresa text NOT NULL,
  nr_voo text NOT NULL,
  icao_origem text NOT NULL,
  icao_destino text NOT NULL,
  dt_referencia date NOT NULL,
  partida_real timestamptz,
  chegada_real timestamptz,
  atraso_partida integer,
  atraso_chegada integer,
  situacao text,
  motivo_alteracao text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT historico_vra_chave_unica UNIQUE (
    ano_mes, icao_empresa, nr_voo, icao_origem, icao_destino, dt_referencia
  )
);

CREATE INDEX IF NOT EXISTS historico_vra_origem_periodo_idx
  ON public.historico_vra (icao_origem, ano_mes, dt_referencia);
CREATE INDEX IF NOT EXISTS historico_vra_destino_periodo_idx
  ON public.historico_vra (icao_destino, ano_mes, dt_referencia);

ALTER TABLE public.historico_vra ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Leitura publica do historico VRA" ON public.historico_vra;
CREATE POLICY "Leitura publica do historico VRA"
  ON public.historico_vra FOR SELECT TO anon USING (true);

GRANT SELECT ON TABLE public.historico_vra TO anon;
GRANT ALL ON TABLE public.historico_vra TO service_role;
