-- Esquema do painel de voos SIROS/ANAC.
-- Execute no SQL Editor do Supabase antes de configurar os GitHub Secrets.

CREATE TABLE IF NOT EXISTS public.voos (
  id bigint generated by default as identity primary key,
  data_referencia date not null,
  icao_empresa text,
  nome_empresa text not null,
  numero_voo text not null,
  etapa text not null default '1',
  icao_origem text not null,
  icao_destino text not null,
  hr_partida_utc time,
  hr_chegada_utc time,
  partida_iso timestamptz,
  chegada_iso timestamptz,
  equipamento text,
  assentos integer check (assentos is null or assentos >= 0),
  tipo_operacao text,
  tipo_servico text,
  criado_em timestamptz not null default now(),
  atualizado_em timestamptz not null default now(),
  CONSTRAINT voos_chave_unica UNIQUE (
    data_referencia,
    icao_empresa,
    numero_voo,
    icao_origem,
    icao_destino,
    etapa
  )
);

CREATE TABLE IF NOT EXISTS public.execucoes (
  id bigint generated by default as identity primary key,
  concluido_em timestamptz not null,
  aeroportos_buscados text[] not null,
  voos_inseridos integer not null default 0 check (voos_inseridos >= 0),
  voos_atualizados integer not null default 0 check (voos_atualizados >= 0),
  status text not null,
  observacao text
);

-- Métricas detalhadas usadas pelo pipeline v2. ALTER TABLE torna a alteração
-- compatível com projetos que já haviam executado a versão anterior do schema.
ALTER TABLE public.execucoes
  ADD COLUMN IF NOT EXISTS voos_processados integer NOT NULL DEFAULT 0 CHECK (voos_processados >= 0),
  ADD COLUMN IF NOT EXISTS lotes_enviados integer NOT NULL DEFAULT 0 CHECK (lotes_enviados >= 0),
  ADD COLUMN IF NOT EXISTS erros integer NOT NULL DEFAULT 0 CHECK (erros >= 0);

CREATE TABLE IF NOT EXISTS public.historico_vra (
  id bigint generated by default as identity primary key,
  ano_mes text NOT NULL CHECK (ano_mes ~ '^\\d{4}-\\d{2}$'),
  icao_empresa text NOT NULL,
  nr_voo text NOT NULL,
  icao_origem text NOT NULL,
  icao_destino text NOT NULL,
  dt_referencia date NOT NULL,
  partida_real timestamptz,
  chegada_real timestamptz,
  atraso_partida integer,
  atraso_chegada integer,
  situacao text,
  motivo_alteracao text,
  criado_em timestamptz NOT NULL DEFAULT now(),
  atualizado_em timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT historico_vra_chave_unica UNIQUE (
    ano_mes, icao_empresa, nr_voo, icao_origem, icao_destino, dt_referencia
  )
);

CREATE INDEX IF NOT EXISTS voos_destino_data_chegada_idx
  on public.voos (icao_destino, data_referencia, chegada_iso);
CREATE INDEX IF NOT EXISTS voos_origem_data_partida_idx
  on public.voos (icao_origem, data_referencia, partida_iso);
CREATE INDEX IF NOT EXISTS execucoes_concluido_em_idx
  on public.execucoes (concluido_em desc);
CREATE INDEX IF NOT EXISTS historico_vra_origem_periodo_idx
  on public.historico_vra (icao_origem, ano_mes, dt_referencia);
CREATE INDEX IF NOT EXISTS historico_vra_destino_periodo_idx
  on public.historico_vra (icao_destino, ano_mes, dt_referencia);

ALTER TABLE public.voos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.execucoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.historico_vra ENABLE ROW LEVEL SECURITY;

-- O painel publico so consulta dados. Escrita ocorre exclusivamente no workflow
-- autenticado com a chave de servico, que nao deve ser exposta no navegador.
CREATE POLICY "Leitura publica dos voos"
  on public.voos for select to anon
  using (true);
CREATE POLICY "Leitura publica das execucoes"
  on public.execucoes for select to anon
  using (true);
CREATE POLICY "Leitura publica do historico VRA"
  on public.historico_vra for select to anon
  using (true);

GRANT SELECT ON TABLE public.voos TO anon;
GRANT SELECT ON TABLE public.execucoes TO anon;
GRANT SELECT ON TABLE public.historico_vra TO anon;
GRANT ALL ON TABLE public.voos TO service_role;
GRANT ALL ON TABLE public.execucoes TO service_role;
GRANT ALL ON TABLE public.historico_vra TO service_role;
